### ISSUE TITLE
Sim Data/Imports

### ISSUE THREAD

**Issue by Missbzeebee** [Zerbu/Mod-Constructor-5#13]
At the moment of writing this, I am unable to add Sim data to my file so I went into S4S and wrote some code for the pie menu category, parents, and base. If you could either add pie menus and add support for importing your old files from Mod Constructor 4 or add the ability to import from any .package. sorry, I know this would be a lot of work, but I would appreciate it and I know other simmers would too. for the moment I'm going to go back to using v4 so if it is possible to be able to import that would be great!

Thanks,
Modder Bzeebee

**Comment by Zerbu** [comment]
Thanks for the suggestions!

Pie Menu Categories are currently on the to-do list to be added in a future update :)

The ability to merge two package together on export (which could be used for what you're describing) is something I've been considering for a while, but was low priority. Since you've mentioned a use for it, I'll prioritize it.
