### ISSUE TITLE
Traits conflicts

### ISSUE THREAD

**Issue by QWERTYIOUS** [Zerbu/Mod-Constructor-5#49]
I would like to add a features that my custom traits can be conflicts with other traits.

**Comment by Zerbu** [comment]
It's currently not possible with Mod Constructor, and because of how trait conflicts are coded, it would be very tricky to add. Trait conflicts are defined in SimData, and doing anything beyond fixed-length hex replacements with SimData is very complicated. There is also the problem that setting a custom trait to conflict with an EA trait would only prevent the EA trait from being selected after the custom trait, not the other way around.
