### ISSUE TITLE
Exporting to Test

### ISSUE THREAD

**Issue by galaxyofwallflowers** [Zerbu/Mod-Constructor-5#9]
I'm trying to export the mod to see if the XML labels changed with what I did in the Element Settings but I am getting this error.
![image](https://user-images.githubusercontent.com/85098089/150003569-b8ab17aa-a7a5-4124-9c6f-4be2ec12056b.png)
I am pretty sure I put in all information correctly.
![image](https://user-images.githubusercontent.com/85098089/150003823-3374b03e-2560-49fd-970d-86777da9c27c.png)
![image](https://user-images.githubusercontent.com/85098089/150008109-f746a692-1114-47a8-8857-d4257bf7db41.png)
![image](https://user-images.githubusercontent.com/85098089/150008207-8bac9679-d178-4322-b3e0-2f1dd7d53bec.png)

**Comment by Zerbu** [comment]
In one of your screenshots, the instance part of the icon is "(22)" which isn't a valid instance key. Did you input that manually or did Mod Constructor do that automatically? If it's the latter, it's a bug, but if it's the former, it's a user error.

Either way, I'll make it so that in the next update, it shows a custom error message instead of a vague programming error message.

**Comment by galaxyofwallflowers** [comment]
Thank you. And itcdid that automatically. How do I go about making it blend with other buffs?

**Comment by galaxyofwallflowers** [comment]
Okay thank you again for the help. I moved it to import as a custom image and it let me export
